### ISSUE TITLE
How to setup it with my project?

### ISSUE THREAD

**Issue by paulocoutinhox** [hwhsu1231/cmake-conan-setup#9]
Hi,

I ready your project description and i think that it solve my problem. 

I need a non-intrusive form of build my dependencies (openssl, poco, zlib, etc) for mac, win, linux, ios, android and webassembly.

Im already doing it with project CPM and now i want add support for conan in my project XPLPC: https://github.com/xplpc/xplpc

Is possible use it in my case?

The main problem to me is with Android, iOS and WebAssembly, because the profile need:

IOS:
```
[tool_requires]
darwin-toolchain/1.0.0@xplpc/stable
```

ANDROID:
```
[tool_requires]
android-ndk/r25
```

WASM:
```
[tool_requires]
emsdk/3.1.31
```

And i need build for ios (ios, simulator, tvos, watchos etc), so i will need use profiles for each platforms like in my other project: https://github.com/nativium/nativium/tree/main/conan/profiles ?

Can you help me with these answers?

Thanks.

**Comment by hwhsu1231** [comment]
Hi @paulocoutinhox. Thanks for your reading!!

> Is possible use it in my case?

Theoratically, it should be.

But first of all, I might not be able to help the platforms you mentioned, iOS, Andoird, and WASM, since I haven't had enough experience/knowledge on them.

The main reason why I proposed this project is to tell Conan Team that there is an alternative way to solve the CAE problem caused by CMakeToolchain generator (see more details on: https://github.com/conan-io/cmake-conan/issues/447), which is:

> Use a subproccess to run `conan install` command to generate `conan_toolchain.cmake` when injection.

And recently, Conan Team has upgraded the cmake-conan to [develop2](https://github.com/conan-io/cmake-conan/tree/develop2), and they started to put more efforts on improving and maintaining it. I think it's great, but it still don't solve the CAE problem currently. Therefore, I opened an issue to suggest Conan Team to take the technique that I used in this project into consideration.

* https://github.com/conan-io/cmake-conan/issues/488

If cmake-conan starts to adopt the technique that I used in this project, then I think the mission of this project has been accomplished. Maybe you can share your ideas/problems/demands on the above link.

Hope my replies can help you.

**Comment by paulocoutinhox** [comment]
Hi,

Thanks for answer.

I already post there before: https://github.com/conan-io/cmake-conan/issues/495

Anyway, thanks, i will close the issue.
